# Generated by Django 5.2.8 on 2025-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='draw_delay_days',
            field=models.PositiveIntegerField(default=3, help_text='Days to wait after unlock before draw'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, help_text='When min_participants was reached', null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_selection_hash',
            field=models.CharField(blank=True, help_text='Hash used for winner selection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_selection_seed',
            field=models.CharField(blank=True, help_text='Public seed for transparent selection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_selection_timestamp',
            field=models.DateTimeField(blank=True, help_text='When winner was selected', null=True),
        ),
    ]
