# Generated by Django 5.2.8 on 2025-12-02 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_raffle_draw_delay_days_raffle_unlocked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='raffle',
            old_name='min_participants_to_unlock',
            new_name='min_entries_to_unlock',
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('user', 'raffle')},
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='cost_tokens',
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of entries this record represents'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, help_text='When min_entries was reached', null=True),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='cost_tokens',
        ),
    ]
