# Generated by Django 5.2.8 on 2025-12-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_rename_min_participants_to_unlock_raffle_min_entries_to_unlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='quantity_bonus',
            field=models.PositiveIntegerField(default=0, help_text='Number of bonus entries this record represents'),
        ),
    ]
