# Generated by Django 5.2.8 on 2025-12-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_entry_quantity_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COUNTDOWN', 'Countdown'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], default='OPEN', max_length=20),
        ),
    ]
