# Generated by Django 5.2.8 on 2025-12-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('select_winner', 'Select Winner'), ('notify_starting', 'Notify Raffle Starting')], max_length=50),
        ),
    ]
