# Generated by Django 5.2.8 on 2025-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_prize_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_credits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reward_tokens',
        ),
        migrations.AddField(
            model_name='product',
            name='entries_per_product',
            field=models.PositiveIntegerField(default=1, help_text='Number of entries granted per purchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price in real money', max_digits=12),
            preserve_default=False,
        ),
    ]
