# Generated by Django 5.2.8 on 2025-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
