# Generated by Django 5.2.8 on 2025-12-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_prize_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
