# Generated by Django 5.2.8 on 2025-12-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenTransaction',
        ),
    ]
