# Generated by Django 5.2.8 on 2025-12-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_credit_balance_user_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_balance',
        ),
    ]
